services:
  app:
    container_name: metamcp_production
    image: ghcr.io/metatool-ai/metamcp:latest
    pull_policy: always
    env_file:
      - .env
    ports:
      - "12008:12008"
      - "12009:12009"
    environment:
      # Postgres connection details (Supabase)
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

      # Database configuration (composed from above vars)
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT:-5432}/${POSTGRES_DB}

      # Application URL configuration
      APP_URL: ${APP_URL}
      NEXT_PUBLIC_APP_URL: ${APP_URL}
      
      # Auth configuration
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      
      TRANSFORM_LOCALHOST_TO_DOCKER_INTERNAL: ${TRANSFORM_LOCALHOST_TO_DOCKER_INTERNAL:-false}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - metamcp-network

networks:
  metamcp-network:
    driver: bridge